/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import repositories.Repositories_TTPhong;
import Model.Model_DSPhong;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import repositories.Repositories_TTKH6;
import Model.Model_DatPhong;
import javax.swing.JOptionPane;
import Model.Model_HDC6;
import repositories.Repositories_HDC6;
import Model.Model_HD3;
import java.util.Date;
import repositories.Repositories_HD6;
import java.time.temporal.ChronoUnit;
import java.time.LocalDate;
import java.time.ZoneId;
import Model.Model_DP3;
import java.util.Calendar;
import repositories.Repositories_DP3;
import view.view_DichVu;
import repositories.Repositories_ChiTiet;
import Model.Model_ChiTietPhong;
/**
 *
 * @author Chi Dat
 */
public class View_DatPhong6 extends javax.swing.JFrame {
    private Repositories_TTPhong rp_Dsp = new Repositories_TTPhong();
    private DefaultTableModel mol_DP = new DefaultTableModel();
    private int i =- 1;
    private Repositories_TTKH6 rp_TTKH = new Repositories_TTKH6();
    private Repositories_HDC6 rp_HDC = new Repositories_HDC6();
    private Repositories_HD6 rp_HD = new Repositories_HD6();
    private Repositories_DP3 rp_HDCT = new Repositories_DP3();
    private View.View_Login lg = new View_Login();
    public String maNV = Model.Model_luuTru.getMaNV();
    private Repositories_ChiTiet rp_CT = new Repositories_ChiTiet();
     private String tenNV = Model.Model_luuTru.gettenNV();
    /**
     * Creates new form View_DatPhong6
     */
    
    public View_DatPhong6() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_MaNV.setEnabled(false);
        txt_TenNhanVien.setEnabled(false);
        txt_TongTienPhong.setEnabled(false);
        this.fillTable_Dsp(rp_Dsp.getAll_DSPhong());
        this.fillTable_KH(rp_TTKH.getAll_KH());
        this.fillTable_HDC(rp_HDC.getAll_HDC6());
        
       txt_TenNhanVien.setText(tenNV);
        txt_MaNV.setText(maNV);
    }
    private void fillTable_Dsp(ArrayList<Model_DSPhong> list_Dsp){
        mol_DP = (DefaultTableModel) tbl_Dsp.getModel();
        mol_DP.setRowCount(0);
        for (Model_DSPhong dsp : list_Dsp) {
            mol_DP.addRow(dsp.toDaTa_DSPhong());
        }
                
    }
    private void fillTable_KH(ArrayList<Model_DatPhong> list_KH){
        mol_DP = (DefaultTableModel) tbl_KH.getModel();
        mol_DP.setRowCount(0);
        for (Model_DatPhong kh : list_KH) {
            mol_DP.addRow(kh.toDataRows_KH1());
        }
               
    }
    private void fillTable_HDC(ArrayList<Model_HDC6>list_HDC){
        mol_DP = (DefaultTableModel) tbl_HoaDonCho.getModel();
        mol_DP.setRowCount(0);
        for (Model_HDC6 model_HDC6 : list_HDC) {
            mol_DP.addRow(model_HDC6.toData_HDC6());
        }
    }
      private void timKiem_TTP(String keyword) {
    Repositories_TTPhong repo = new Repositories_TTPhong(); // Tạo đối tượng từ repositories
    ArrayList<Model_DSPhong> list = repo.timKiem_TTPhong(keyword); // Gọi hàm tìm kiếm
    
    if (list.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Không tìm thấy phòng nào với từ khóa: " + keyword);
    } else {
        JOptionPane.showMessageDialog(null, "Đã tìm thấy " + list.size() + " phòng với từ khóa: " + keyword);
        updateTable(list); // Cập nhật bảng dữ liệu dựa trên kết quả tìm kiếm
    }
}

private void updateTable(ArrayList<Model_DSPhong> list) {
    DefaultTableModel model = (DefaultTableModel) tbl_Dsp.getModel();
    model.setRowCount(0);
    for (Model_DSPhong item : list) {
        model.addRow(new Object[]{
            item.getTang(),
            item.getMaPhong(),
            item.getTinhTrang(),
            item.getLoaiPhong(),
            item.getGiaPhong(),
            item.getSoNguoiO(),
            item.getMoTa()
        });
    }
}
private void fillTable_ChiTiet(ArrayList<Model_ChiTietPhong> list_ChiTiet){
    mol_DP = (DefaultTableModel) tbl_ChiTietPhong.getModel();
    mol_DP.setRowCount(0);
    for (Model_ChiTietPhong chiTiet : list_ChiTiet) {
        mol_DP.addRow(chiTiet.toData_ChiTiet());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_Dsp = new javax.swing.JTable();
        btn_TimKiem = new javax.swing.JButton();
        txt_TimKiem = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_maPhong = new javax.swing.JTextField();
        txt_LoaiPhong = new javax.swing.JTextField();
        txt_GiaPhong = new javax.swing.JTextField();
        txt_TongTienPhong = new javax.swing.JTextField();
        txt_SoNguoiO = new javax.swing.JTextField();
        btn_TinhTienPhong = new javax.swing.JButton();
        btn_LuuDatPhong = new javax.swing.JButton();
        btn_DatDichVu = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        jdc_CheckOut = new com.toedter.calendar.JDateChooser();
        jdc_CheckIn = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HoaDonCho = new javax.swing.JTable();
        btn_TaoHD = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_ChiTietPhong = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_MaHD = new javax.swing.JTextField();
        txt_MaNV = new javax.swing.JTextField();
        txt_MaKH = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        txt_DiaChi = new javax.swing.JTextField();
        txt_TienCoc = new javax.swing.JTextField();
        btn_LuuHD = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_KH = new javax.swing.JTable();
        btn_TimKiemKH = new javax.swing.JButton();
        txt_TimKiemKH = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_TenKH = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_TenNhanVien = new javax.swing.JTextField();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_Dsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tầng", "Phòng", "Tình Trạng", "Loại Phòng", "Giá", "Số người ở", "Mô tả"
            }
        ));
        tbl_Dsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DspMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_Dsp);

        btn_TimKiem.setText("Tìm kiếm:");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_TimKiem)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TimKiem)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TimKiem)
                    .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Đặt Phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setText("Check In:");

        jLabel10.setText("Check Out:");

        jLabel11.setText("Mã Phòng:");

        jLabel12.setText("Loại Phòng:");

        jLabel13.setText("Số người ở:");

        jLabel14.setText("Giá Phòng");

        jLabel15.setText("Tổng Tiền Phòng:");

        btn_TinhTienPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_TinhTienPhong.setText("Tính Tiền Phòng");
        btn_TinhTienPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TinhTienPhongActionPerformed(evt);
            }
        });

        btn_LuuDatPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LuuDatPhong.setText("Đặt Phòng");
        btn_LuuDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuDatPhongActionPerformed(evt);
            }
        });

        btn_DatDichVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_DatDichVu.setText("Đặt Dịch Vụ");
        btn_DatDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DatDichVuActionPerformed(evt);
            }
        });

        btn_Thoat.setBackground(new java.awt.Color(204, 255, 255));
        btn_Thoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Thoat.setText("CANCEL");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });

        jdc_CheckOut.setDateFormatString("yyyy-MM-dd");

        jdc_CheckIn.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Thoat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_DatDichVu)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                        .addComponent(txt_SoNguoiO, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(54, 54, 54)
                                        .addComponent(txt_GiaPhong))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_LoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_maPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_TinhTienPhong)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel10)))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_LuuDatPhong)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdc_CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_TongTienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdc_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txt_maPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_LoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_SoNguoiO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jdc_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jdc_CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_GiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txt_TongTienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Thoat)
                    .addComponent(btn_DatDichVu)
                    .addComponent(btn_TinhTienPhong)
                    .addComponent(btn_LuuDatPhong)))
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn Chờ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_HoaDonCho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã HĐ", "Ngày Xuất Đơn", "Trạng thái"
            }
        ));
        tbl_HoaDonCho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HoaDonChoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_HoaDonCho);
        if (tbl_HoaDonCho.getColumnModel().getColumnCount() > 0) {
            tbl_HoaDonCho.getColumnModel().getColumn(0).setHeaderValue("Mã HDCT");
        }

        btn_TaoHD.setBackground(new java.awt.Color(204, 204, 204));
        btn_TaoHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_TaoHD.setText("Tạo Hóa Đơn");
        btn_TaoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btn_TaoHD)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btn_TaoHD)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết phòng đã thuê", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_ChiTietPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Phòng", "Tên Khách Hàng"
            }
        ));
        tbl_ChiTietPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ChiTietPhongMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_ChiTietPhong);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Thông tin Hóa Đơn");

        jLabel3.setText("Mã HĐ:");

        jLabel4.setText("Mã NV:");

        jLabel5.setText("Mã KH:");

        jLabel6.setText("SĐT:");

        jLabel7.setText("Địa Chỉ:");

        jLabel8.setText("Tiền Cọc:");

        btn_LuuHD.setBackground(new java.awt.Color(204, 204, 204));
        btn_LuuHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LuuHD.setText("Lưu Thông Tin");
        btn_LuuHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuHDActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_KH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên Khách Hàng", "Ngày Sinh", "CCCD", "SĐT", "Email", "Giới tính", "Địa Chỉ"
            }
        ));
        tbl_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KHMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_KH);

        btn_TimKiemKH.setText("Tìm Kiếm");
        btn_TimKiemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemKHActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Check Thông tin Khách Hàng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btn_Reset.setBackground(new java.awt.Color(204, 204, 204));
        btn_Reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Reset.setText("Reset");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_TimKiemKH)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TimKiemKH)
                        .addGap(9, 9, 9))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btn_Reset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(185, 185, 185))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TimKiemKH)
                    .addComponent(txt_TimKiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jLabel9.setText("Tên Khách Hàng:");

        jLabel16.setText("Tên Nhân Viên:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel5))))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_DiaChi)
                                    .addComponent(txt_TenKH)
                                    .addComponent(txt_SDT)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(btn_LuuHD))
                                    .addComponent(txt_TienCoc)
                                    .addComponent(txt_MaNV)
                                    .addComponent(txt_TenNhanVien)
                                    .addComponent(txt_MaKH)
                                    .addComponent(txt_MaHD))))
                        .addGap(0, 270, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_TenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txt_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_TienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btn_LuuHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_DspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DspMouseClicked
        // TODO add your handling code here:
        i = tbl_Dsp.getSelectedRow();
        this.showDaTa_Dsp(i);
        txt_maPhong.setEnabled(false);
        txt_LoaiPhong.setEnabled(false);
        txt_GiaPhong.setEnabled(false);
        txt_SoNguoiO.setEnabled(false);
    }//GEN-LAST:event_tbl_DspMouseClicked

    private void tbl_KHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KHMouseClicked
        // TODO add your handling code here:
        i = tbl_KH.getSelectedRow();
        this.showData_KH(i);
        txt_MaKH.setEnabled(false);
        txt_TenKH.setEnabled(false);
        txt_SDT.setEnabled(false);
        txt_DiaChi.setEnabled(false);
    }//GEN-LAST:event_tbl_KHMouseClicked

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn tìm kiếm thông tin");
        if(chon == 0){
        String keyword = txt_TimKiem.getText().trim();
        JOptionPane.showMessageDialog(this, "Đã tìm thấy thông tin");
        timKiem_TTP(keyword);
        }
      
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_TaoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoHDActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn tạo hóa đơn mới");
        if(chon == 0){
            if(rp_HDC.them_HDC6()>0){
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                this.fillTable_HDC(rp_HDC.getAll_HDC6());
            }else{
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        }
    }//GEN-LAST:event_btn_TaoHDActionPerformed

    private void tbl_HoaDonChoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HoaDonChoMouseClicked
        // TODO add your handling code here:
        i = tbl_HoaDonCho.getSelectedRow();
        this.showData_HDC(i);
        txt_MaHD.setEnabled(false);
        String maHD = tbl_HoaDonCho.getValueAt(i, 0).toString();
        this.fillTable_ChiTiet(rp_CT.getAll_ChiTietByMaHD(maHD));
        
    }//GEN-LAST:event_tbl_HoaDonChoMouseClicked

    private void btn_LuuHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuHDActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn lưu thông tin");
        if(chon == 0){
           if(this.readForm_HD6()!= null){
               rp_HD.sua_HD6(txt_MaHD.getText(), this.readForm_HD6());
               JOptionPane.showMessageDialog(this,"Lưu thông tin thành công");
           }
        }
    }//GEN-LAST:event_btn_LuuHDActionPerformed

    private void btn_TimKiemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemKHActionPerformed
        // TODO add your handling code here:
        String maKH = txt_TimKiemKH.getText().trim();
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn tìm kiếm thông tin");
        if( chon == 0){
            if(maKH.isEmpty()){
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin cần tìm kiếm");
            }else{
                ArrayList<Model_DatPhong> list_TimKiem = rp_TTKH.timKiem_KH(maKH);
                if(list_TimKiem.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Ko tìm thấy thông tin");
                }else{
                    JOptionPane.showMessageDialog(this, "Đã tìm thấy thông tin");
                    this.fillTable_KH(list_TimKiem);
                }
            }
        }
    }//GEN-LAST:event_btn_TimKiemKHActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        View_QLKH qlkh = new View_QLKH();
        qlkh.setDefaultCloseOperation(qlkh.DISPOSE_ON_CLOSE);
        qlkh.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        // TODO add your handling code here:
        this.fillTable_KH(rp_TTKH.getAll_KH());
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void btn_TinhTienPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TinhTienPhongActionPerformed
        // TODO add your handling code here:
//        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn tính tiền phòng");
//    if (chon == 0) {
//        try {
//            double giaPhong = Double.parseDouble(txt_GiaPhong.getText().trim());
//            Date checkIn = jdc_CheckIn.getDate();
//            Date checkOut = jdc_CheckOut.getDate();
//
//            if (checkIn != null && checkOut != null && !checkOut.before(checkIn)) {
//                // Chuyển đổi từ Date sang LocalDate
//                LocalDate checkInLocalDate = checkIn.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
//                LocalDate checkOutLocalDate = checkOut.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
//
//                // Tính số ngày giữa check-in và check-out
//                long daysBetween = ChronoUnit.DAYS.between(checkInLocalDate, checkOutLocalDate);
//                double tongTienPhong = giaPhong * daysBetween;
//
//                // Hiển thị tổng tiền phòng
//                txt_TongTienPhong.setText(String.valueOf(tongTienPhong));
//            } else {
//                JOptionPane.showMessageDialog(this, "Ngày check-out phải sau ngày check-in.", "Lỗi", JOptionPane.ERROR_MESSAGE);
//            }
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Giá phòng không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
//        }
//    }
 int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn tính tiền phòng?");
    if (chon == 0) {
        try {
            double giaPhong = Double.parseDouble(txt_GiaPhong.getText().trim());
            Date checkIn = jdc_CheckIn.getDate();
            Date checkOut = jdc_CheckOut.getDate();

            if (checkIn != null && checkOut != null && !checkOut.before(checkIn)) {
                // Tính số ngày giữa check-in và check-out
                long daysBetween = getDaysBetweenDates(checkIn, checkOut);
                double tongTienPhong = giaPhong * daysBetween;

                // Hiển thị tổng tiền phòng
                txt_TongTienPhong.setText(String.valueOf(tongTienPhong));
            } else {
                JOptionPane.showMessageDialog(this, "Ngày check-out phải sau ngày check-in.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá phòng không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btn_TinhTienPhongActionPerformed

    private void btn_LuuDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuDatPhongActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn lưu thông tin đặt phòng");
        if(chon == 0){
            if(this.readForm_DP3()== null){
                JOptionPane.showMessageDialog(this, "Lưu thất bại");
            }else{
                if(rp_HDCT.them_DP3(this.readForm_DP3())>0){
                    JOptionPane.showMessageDialog(this, "Đặt Phòng thành công");
                    this.fillTable_Dsp(rp_Dsp.getAll_DSPhong());
                    reset_HDCT();
                }else{
                    JOptionPane.showMessageDialog(this, "thêm thất bại");
                }
            }
            
        }
    }//GEN-LAST:event_btn_LuuDatPhongActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        // TODO add your handling code here:
        View_TrangChu tt = new View_TrangChu();
        tt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void btn_DatDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DatDichVuActionPerformed
        // TODO add your handling code here:
        view.view_DichVu dv = new view_DichVu();
        dv.setDefaultCloseOperation(dv.DISPOSE_ON_CLOSE);
        dv.setVisible(true);
    }//GEN-LAST:event_btn_DatDichVuActionPerformed

    private void tbl_ChiTietPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ChiTietPhongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_ChiTietPhongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_DatPhong6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_DatPhong6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_DatPhong6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_DatPhong6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_DatPhong6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DatDichVu;
    private javax.swing.JButton btn_LuuDatPhong;
    private javax.swing.JButton btn_LuuHD;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_TaoHD;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_TimKiemKH;
    private javax.swing.JButton btn_TinhTienPhong;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private com.toedter.calendar.JDateChooser jdc_CheckIn;
    private com.toedter.calendar.JDateChooser jdc_CheckOut;
    private javax.swing.JTable tbl_ChiTietPhong;
    private javax.swing.JTable tbl_Dsp;
    private javax.swing.JTable tbl_HoaDonCho;
    private javax.swing.JTable tbl_KH;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_GiaPhong;
    private javax.swing.JTextField txt_LoaiPhong;
    private javax.swing.JTextField txt_MaHD;
    private javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_SoNguoiO;
    private javax.swing.JTextField txt_TenKH;
    private javax.swing.JTextField txt_TenNhanVien;
    private javax.swing.JTextField txt_TienCoc;
    private javax.swing.JTextField txt_TimKiem;
    private javax.swing.JTextField txt_TimKiemKH;
    private javax.swing.JTextField txt_TongTienPhong;
    private javax.swing.JTextField txt_maPhong;
    // End of variables declaration//GEN-END:variables
void showDaTa_Dsp(int i){
    txt_maPhong.setText(tbl_Dsp.getValueAt(i, 1).toString());
    txt_LoaiPhong.setText(tbl_Dsp.getValueAt(i, 3).toString());
    txt_GiaPhong.setText(tbl_Dsp.getValueAt(i, 4).toString());
    txt_SoNguoiO.setText(tbl_Dsp.getValueAt(i, 5).toString());
}
void showData_KH(int i){
    txt_MaKH.setText(tbl_KH.getValueAt(i, 0).toString());
    txt_TenKH.setText(tbl_KH.getValueAt(i, 1).toString());
    txt_SDT.setText(tbl_KH.getValueAt(i,4).toString());
    txt_DiaChi.setText(tbl_KH.getValueAt(i,7).toString());
    
}
void showData_HDC(int i){
    txt_MaHD.setText(tbl_HoaDonCho.getValueAt(i,0).toString());
}
private Model_HD3 readForm_HD6(){
    String maHD;
    String maKH;
    String maNV;
    String sdt;
    String diaChi;
    double tienCoc;
    maHD = txt_MaHD.getText().trim();
    if(maHD.isEmpty()){
        JOptionPane.showMessageDialog(this, "Bạn chưa điền mã hóa đơn");
        txt_MaHD.requestFocus();
        return null;
    }
    maKH = txt_MaKH.getText().trim();
    if(maKH.isEmpty()){
        JOptionPane.showMessageDialog(this, "Bạn chưa điền mã khách hàng");
        txt_MaKH.requestFocus();
        return null;
    }
    maNV = txt_MaNV.getText().trim();
    if(maNV.isEmpty()){
        JOptionPane.showMessageDialog(this, "Bạn chưa điền mã nhân viên");
        txt_MaNV.requestFocus();
        return null;
    }
    sdt = txt_SDT.getText().trim();
    if(sdt.isEmpty()){
        JOptionPane.showMessageDialog(this, "Bạn chưa điền số điện thoại");
        txt_SDT.requestFocus();
        return null;
    }
    diaChi = txt_DiaChi.getText().trim();
    if(diaChi.isEmpty()){
        JOptionPane.showMessageDialog(this, "Bạn chưa điền địa chỉ");
        txt_DiaChi.requestFocus();
        return null;
    }
    
    try {
        tienCoc = Double.parseDouble(txt_TienCoc.getText().trim());
        if(tienCoc < 0 ){
            JOptionPane.showMessageDialog(this, "Tiền cọc phải là số dương");
            txt_TienCoc.requestFocus();
            return null;
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Tiền cọc ko hợp lệ");
        txt_TienCoc.requestFocus();
        return null;
    }
    return new Model_HD3(maHD, maNV, maKH, sdt, diaChi, tienCoc);
    
}
private Model_DP3 readForm_DP3(){
    String maHD;
    String maPhong;
    Date checkIn;
    Date checkOut;
    double tienPhong;
    maHD = txt_MaHD.getText().trim();
    if(maHD.isEmpty()){
        JOptionPane.showMessageDialog(this, "Bạn chưa điền mã hóa đơn");
        txt_MaHD.requestFocus();
        return null;
    }
    maPhong = txt_maPhong.getText().trim();
    if(maPhong.isEmpty()){
        JOptionPane.showMessageDialog(this, "Bạn chưa điền mã phòng");
        txt_maPhong.requestFocus();
        return null;
    }
    checkIn = jdc_CheckIn.getDate();
    if(checkIn == null){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn ngày check In");
            jdc_CheckIn.requestFocus();
            return null;
        }
    checkOut = jdc_CheckOut.getDate();
    if(checkOut == null){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn ngày check Out");
            jdc_CheckOut.requestFocus();
            return null;
        }
     if(checkIn.after(checkOut)){
            JOptionPane.showMessageDialog(this, "Dữ liệu ko hợp lệ, ngày check in phải trước ngày check out");
            jdc_CheckIn.requestFocus();
            return null;
        }
    
    try {
        tienPhong = Double.parseDouble(txt_TongTienPhong.getText().trim());
        if(tienPhong < 0){
            JOptionPane.showMessageDialog(this, "Tổng tiền phòng phải là số dương");
            txt_TongTienPhong.requestFocus();
            return null;
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Tổng tiền phòng ko hợp lệ");
        txt_TongTienPhong.requestFocus();
        return null;
                
    }
    return new Model_DP3(maHD, maPhong, checkIn, checkOut, tienPhong);
    
}
void reset_HDCT(){
    txt_maPhong.setText("");
    txt_LoaiPhong.setText("");
    txt_SoNguoiO.setText("");
    txt_GiaPhong.setText("");
    txt_TongTienPhong.setText("");
    //jdc_CheckIn.setDate(null);
    //jdc_CheckOut.setDate(null);
}
private long getDaysBetweenDates(Date startDate, Date endDate) {
    Calendar start = Calendar.getInstance();
    start.setTime(startDate);

    Calendar end = Calendar.getInstance();
    end.setTime(endDate);

    long diffInMillis = end.getTimeInMillis() - start.getTimeInMillis();
    return diffInMillis / (24 * 60 * 60 * 1000); // Chia cho số millisecond trong một ngày
}
  


}
