/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import View.View_TrangChu;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Model_DichVu;

import repositories.Repositories_DichVu;


/**
 *
 * @author rinbo
 */
public class view_DichVu extends javax.swing.JFrame {

    private repositories.Repositories_DichVu rp = new Repositories_DichVu();
    private DefaultTableModel mol = new DefaultTableModel();
    private int i = -1;
     
    /**
     * Creates new form view_DichVu
     */
    public view_DichVu() {
        initComponents();
        this.setLocationRelativeTo(null);
        cbo_LoaiDV.removeAllItems();
        cbo_LoaiDV.addItem("DV Thường+Vip");
        cbo_LoaiDV.addItem("DV VIP");
        cbo_LoaiDV.addItem("DV Thường");
        this.fillTable(rp.getAll_DV());
        this.fillTableDDV(rp.getAll_DV());
        this.fillTable_HDDDV(rp.getAll_HDDDV());
        this.fillTable_HDV(rp.getALL_HDV());
        i = rp.getAll_DV().size();
        this.showDaTa_DV(i - 1);
        tbl_DV.setRowSelectionInterval(i - 1, i - 1);
        // khóa ô 
        txt_maDV.setEnabled(false);
        txt_maHD.setEnabled(false);
        txt_tenDV.setEnabled(false);
        txt_maPhong.setEnabled(false);
        txt_gia.setEnabled(false);
        txt_tongTien.setEnabled(false);
        txt_maDV1.setEnabled(false);
        txt_maHD1.setEnabled(false);
        txt_tenDV1.setEnabled(false);
        txt_maPhong1.setEnabled(false);
        txt_gia1.setEnabled(false);
        txt_tongTien1.setEnabled(false);
        txt_maDDV1.setEnabled(false);
        jsp_SL1.setEnabled(false);
    }

    private void fillTable(ArrayList<model.Model_DichVu> list) {
        mol = (DefaultTableModel) tbl_DV.getModel();
        mol.setRowCount(0);
        for (Model_DichVu x : list) {
            mol.addRow(x.toDaTaRow_DV());

        }
    }
    
    private void fillTableDDV(ArrayList<Model_DichVu> list) {
        mol = (DefaultTableModel) tbl_DDV.getModel();
        mol.setRowCount(0);
        for (Model_DichVu x : list) {
            mol.addRow(x.toDaTaRow_DV());

        }
    }
    private void fillTable_HDDDV(ArrayList<Model_DichVu> list){
        mol = (DefaultTableModel) tbl_HDCTT.getModel();
        mol.setRowCount(0);
        for (Model_DichVu x : list) {
            mol.addRow(x.toDaTaRow_TTHDDV());
        }
    }
    private void fillTable_HDV(ArrayList<Model_DichVu> list){
        mol = (DefaultTableModel) tbl_HDV.getModel();
        mol.setRowCount(0);
        for (Model_DichVu x : list) {
            mol.addRow(x.toDaTaRow_DDV());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_MaDV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_TenDV = new javax.swing.JTextField();
        txt_Gia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_MT = new javax.swing.JTextArea();
        cbo_LoaiDV = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DV = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        tbn_ThemDV = new javax.swing.JButton();
        tbn_Sửa = new javax.swing.JButton();
        Xóa = new javax.swing.JButton();
        tbn_Cancel = new javax.swing.JButton();
        tbn_Reset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tbn_TK = new javax.swing.JButton();
        txt_TK = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_DDV = new javax.swing.JTable();
        txt_TKDV_DDV = new javax.swing.JTextField();
        tbn_TKCDV = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_maHD = new javax.swing.JTextField();
        txt_maDV = new javax.swing.JTextField();
        txt_maDDV = new javax.swing.JTextField();
        txt_tenDV = new javax.swing.JTextField();
        txt_gia = new javax.swing.JTextField();
        txt_tongTien = new javax.swing.JTextField();
        txt_maPhong = new javax.swing.JTextField();
        jsp_SL = new javax.swing.JSpinner();
        btn_tinhToan = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_HDCTT = new javax.swing.JTable();
        txt_TKHDCTT = new javax.swing.JTextField();
        tbn_TKCHD = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_HDV = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_maHD1 = new javax.swing.JTextField();
        txt_maDV1 = new javax.swing.JTextField();
        txt_maDDV1 = new javax.swing.JTextField();
        txt_tenDV1 = new javax.swing.JTextField();
        txt_gia1 = new javax.swing.JTextField();
        txt_tongTien1 = new javax.swing.JTextField();
        txt_maPhong1 = new javax.swing.JTextField();
        jsp_SL1 = new javax.swing.JSpinner();
        btn_luu1 = new javax.swing.JButton();
        btn_cancel1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        txt_TKHDV = new javax.swing.JTextField();
        tbn_TKHDV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(51, 255, 204));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setForeground(new java.awt.Color(153, 255, 204));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Mã Dịch Vụ:");

        txt_MaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaDVActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên Dịch Vụ:");

        txt_Gia.setToolTipText("");
        txt_Gia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GiaActionPerformed(evt);
            }
        });

        jLabel3.setText("Giá Dịch Vụ:");

        jLabel4.setText("Mô Tả:");

        txt_MT.setColumns(20);
        txt_MT.setRows(5);
        jScrollPane2.setViewportView(txt_MT);

        cbo_LoaiDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_LoaiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_LoaiDVActionPerformed(evt);
            }
        });

        jLabel5.setText("Loại Dịch Vụ:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_MaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(cbo_LoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_TenDV, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txt_Gia))))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_MaDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_TenDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(cbo_LoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_DV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Dịch Vụ", "Tên Dịch Vụ", "Giá", "Loại Dịch Vụ", "Mô Tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_DV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_DV);

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbn_ThemDV.setText("Thêm ");
        tbn_ThemDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_ThemDVActionPerformed(evt);
            }
        });

        tbn_Sửa.setText("Sửa");
        tbn_Sửa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_SửaActionPerformed(evt);
            }
        });

        Xóa.setText("Xóa");
        Xóa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XóaActionPerformed(evt);
            }
        });

        tbn_Cancel.setText("Cancel");
        tbn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_CancelActionPerformed(evt);
            }
        });

        tbn_Reset.setText("Reset");
        tbn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Xóa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbn_Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbn_ThemDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbn_Sửa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbn_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbn_ThemDV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbn_Sửa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Xóa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbn_Reset)
                .addGap(12, 12, 12)
                .addComponent(tbn_Cancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setText("DỊCH VỤ");

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));

        tbn_TK.setText("Tìm Kiếm");
        tbn_TK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_TKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(txt_TK)
                .addGap(18, 18, 18)
                .addComponent(tbn_TK)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbn_TK)
                    .addComponent(txt_TK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(264, 264, 264))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dịch Vụ", jPanel1);

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn Dịch Vụ"));

        tbl_DDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Dịch Vụ", "Tên Dịch Vụ", "Giá", "Mô tả", "Loại Dịch Vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_DDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DDVMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_DDV);

        tbn_TKCDV.setText("Tìm Kiếm");
        tbn_TKCDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_TKCDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txt_TKDV_DDV, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(tbn_TKCDV)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbn_TKCDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_TKDV_DDV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Đặt Dịch Vụ"));

        jLabel7.setText("Mã HD:");

        jLabel8.setText("Mã DV:");

        jLabel9.setText("Tên Dịch Vụ:");

        jLabel10.setText("Mã Đặt Dịch Vụ:");

        jLabel11.setText("Số Lượng:");

        jLabel12.setText("Giá:");

        jLabel13.setText("Tổng Tiền:");

        jLabel14.setText("Mã Phòng:");

        txt_maDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maDVActionPerformed(evt);
            }
        });

        btn_tinhToan.setText("Tính Toán");
        btn_tinhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tinhToanActionPerformed(evt);
            }
        });

        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_maHD, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(txt_maDV)
                            .addComponent(txt_maDDV)
                            .addComponent(txt_tenDV)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btn_tinhToan)))
                .addGap(110, 110, 110)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_maPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsp_SL, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_maHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsp_SL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_maDDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_tenDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel)
                    .addComponent(btn_tinhToan)
                    .addComponent(btn_luu)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa Đơn Chưa Thanh Toán"));

        tbl_HDCTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đon", "Mã Phòng", "Tên Khách Hàng", "Số Điện Thoại", "CCCD"
            }
        ));
        tbl_HDCTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HDCTTMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_HDCTT);

        txt_TKHDCTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TKHDCTTActionPerformed(evt);
            }
        });

        tbn_TKCHD.setText("Tìm Kiếm");
        tbn_TKCHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_TKCHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(txt_TKHDCTT, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbn_TKCHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TKHDCTT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbn_TKCHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Đặt Dịch Vụ", jPanel5);

        jPanel10.setBackground(new java.awt.Color(153, 153, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Dịch Vụ Chưa Thanh Toán"));
        jPanel10.setForeground(new java.awt.Color(153, 153, 255));

        tbl_HDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Đặt Dịch Vụ", "Mã Phòng", "Mã Dịch Vụ", "Tên Dịch Vụ", "Số Lượng ", "Giá", "Ngày Đặt", "Tổng Tiền", "Mã Hóa Đơn"
            }
        ));
        tbl_HDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HDVMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_HDV);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Hủy Dịch Vụ Đã Đặt"));

        jLabel15.setText("Mã HD:");

        jLabel16.setText("Mã DV:");

        jLabel17.setText("Tên Dịch Vụ:");

        jLabel18.setText("Mã Đặt Dịch Vụ:");

        jLabel19.setText("Số Lượng:");

        jLabel20.setText("Giá:");

        jLabel21.setText("Tổng Tiền:");

        jLabel22.setText("Mã Phòng:");

        txt_maDV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maDV1ActionPerformed(evt);
            }
        });

        btn_luu1.setText("Hủy Dịch Vụ");
        btn_luu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luu1ActionPerformed(evt);
            }
        });

        btn_cancel1.setText("Cancel");
        btn_cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_maHD1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(txt_maDV1)
                            .addComponent(txt_maDDV1)
                            .addComponent(txt_tenDV1))
                        .addGap(110, 110, 110)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_maPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsp_SL1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gia1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btn_luu1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_maHD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maDV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsp_SL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_maDDV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_tenDV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(33, 33, 33)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel1)
                    .addComponent(btn_luu1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(204, 204, 255));

        tbn_TKHDV.setText("Tìm Kiếm");
        tbn_TKHDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_TKHDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(txt_TKHDV, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbn_TKHDV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TKHDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbn_TKHDV))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 274, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dịch Vụ Chưa Thanh Toán", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XóaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XóaActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "bạn có muốn xóa dữ liệu");
        if (chon == 0) {
            i = tbl_DV.getSelectedRow();
            if (i == -1) {
                JOptionPane.showMessageDialog(this, "bạn chưa chọn dòng");
            } else {
                if (this.readForm() != null) {
                    String maDV = tbl_DV.getValueAt(i, 0).toString();
                    if (rp.xoa(maDV) > 0) {
                        JOptionPane.showMessageDialog(this, "xóa thành công");
                        this.fillTable(rp.getAll_DV());
                    } else {
                        JOptionPane.showMessageDialog(this, "Mã Dịch Vụ Đã được sử dụng không thể xóa");
                    }
                }
            }
        }

    }//GEN-LAST:event_XóaActionPerformed

    private void tbn_SửaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_SửaActionPerformed
        // TODO add your handling code here:
        i = tbl_DV.getSelectedRow();
        int chon = JOptionPane.showConfirmDialog(this, "bạn có muốn sửa dữ liệu");
        if (chon == 0) {
            if (i == -1) {
                JOptionPane.showMessageDialog(this, "bạn chưa chọn dòng");
            } else {
                String maDV = tbl_DV.getValueAt(i, 0).toString();
                if (this.readForm() != null) {
                    if (rp.sua_DV(maDV, this.readForm()) > 0) {
                        JOptionPane.showMessageDialog(this, "sửa thành công");
                        this.fillTable(rp.getAll_DV());
                        this.fillTableDDV(rp.getAll_DV());
                    } else {
                        JOptionPane.showMessageDialog(this, "sửa thất bại");
                    }
                }
            }
        }

    }//GEN-LAST:event_tbn_SửaActionPerformed

    private void tbn_ThemDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_ThemDVActionPerformed
        int chon = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Thêm Dịch Vụ Không ");
        if (chon == JOptionPane.YES_OPTION) {
            if(this.readForm() != null){
                String maDV = txt_MaDV.getText().trim();
                //kiểm tra trùng lặp
                String errorMessage = rp.checkTrung(maDV);
                if(errorMessage != null){
                    JOptionPane.showMessageDialog(this, errorMessage);
                }
                else{
                    //Thực hiện thêm NV
                    if(rp.them_DV(this.readForm())>0){
                        JOptionPane.showMessageDialog(this, "Thêm Thành Công");
                        this.fillTable(rp.getAll_DV());
                       
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Thêm Thất Bại");
                    }
                }
            }        
        }


    }//GEN-LAST:event_tbn_ThemDVActionPerformed

    private void tbl_DVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DVMouseClicked
        // TODO add your handling code here:
        i = tbl_DV.getSelectedRow();
        this.showDaTa_DV(i);
        txt_MaDV.disable();
    }//GEN-LAST:event_tbl_DVMouseClicked

    private void cbo_LoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_LoaiDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_LoaiDVActionPerformed

    private void txt_GiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GiaActionPerformed
        // TODO add your handling code here

    }//GEN-LAST:event_txt_GiaActionPerformed

    private void txt_MaDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaDVActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_MaDVActionPerformed

    private void tbn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_CancelActionPerformed
        // TODO add your handling code here:
        View.View_TrangChu tc = new View_TrangChu();
        tc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tbn_CancelActionPerformed

    private void tbn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_ResetActionPerformed
        // TODO add your handling code here:
        txt_MaDV.setText("");
        txt_TenDV.setText("");
        txt_Gia.setText("");
        txt_MT.setText("");
        txt_MaDV.setEnabled(true);
        this.fillTable(rp.getAll_DV());
    }//GEN-LAST:event_tbn_ResetActionPerformed

    private void tbn_TKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_TKActionPerformed
        // TODO add your handling code here:
        String timKiem = txt_TK.getText().trim();
        if (timKiem.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập mã dịch vụ");
        } else {
            ArrayList<Model_DichVu> KQTK = rp.timKiem(timKiem);
            if (KQTK.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã không tồn tại");
            } else {
                JOptionPane.showMessageDialog(this, "đã thấy dữ liệu");
                this.fillTable(KQTK);
            }
        }
    }//GEN-LAST:event_tbn_TKActionPerformed

    private void txt_maDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maDVActionPerformed

    private void tbl_DDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DDVMouseClicked
        i = tbl_DDV.getSelectedRow();
        this.showDaTa_DDV(i);
        
    }//GEN-LAST:event_tbl_DDVMouseClicked

    private void tbl_HDCTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HDCTTMouseClicked
        // TODO add your handling code here:
        i = tbl_HDCTT.getSelectedRow();
        this.showDaTa_HDDDV();
    }//GEN-LAST:event_tbl_HDCTTMouseClicked

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn chắn chắn muốn lưu thông tin này?");
        if (chon == 0) {
            if (this.readForm_DDV()!= null) {
                String maDDV = txt_maDDV.getText().trim();
                //kiểm tra trùng lặp
                String errorMessage = rp.checkTrung_DDV(maDDV);
                if (errorMessage != null) {
                    JOptionPane.showMessageDialog(this, errorMessage);
                }else{
                    if (rp.them_DDV(this.readForm_DDV())>0) {
                    JOptionPane.showMessageDialog(this, "đặt dịch vụ thành công");
                    this.fillTable_HDV(rp.getALL_HDV());
                }else{
                    JOptionPane.showMessageDialog(this, "đặt dịch vụ thất bại");
                }
                }
                
            }
        }
        txt_tongTien.setText("");
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_tinhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tinhToanActionPerformed
        // TODO add your handling code here:
        int sL = Integer.parseInt(jsp_SL.getValue().toString());
        double gia = Double.parseDouble(txt_gia.getText());
        double tongTien = sL*gia;
        String checkSL = jsp_SL.getValue().toString() ;
        String checKgia = txt_gia.getText();
        if (checkSL.isEmpty()) {
           JOptionPane.showMessageDialog(this, "chưa có dữ liệu để tính toán, kiểm tra lại chưa có dữ liệu ở giá hoặc số lượng");
           return;
        }else{
            
            txt_tongTien.setText(String.valueOf(tongTien));
        }
        
    }//GEN-LAST:event_btn_tinhToanActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        View_TrangChu tc = new View_TrangChu();
        tc.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void tbn_TKCDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_TKCDVActionPerformed
        // TODO add your handling code here:
        String timKiem = txt_TKDV_DDV.getText().trim();
        if (timKiem.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập mã dịch vụ");
        } else {
            ArrayList<Model_DichVu> KQTK = rp.timKiem(timKiem);
            if (KQTK.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã không tồn tại");
            } else {
                JOptionPane.showMessageDialog(this, "đã thấy dữ liệu");
                this.fillTableDDV(KQTK);
            }
        }
    }//GEN-LAST:event_tbn_TKCDVActionPerformed

    private void txt_TKHDCTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TKHDCTTActionPerformed
        // TODO add your handling code here:
        String maTK = txt_TKHDCTT.getText().trim();
        if(maTK.isEmpty()){
            JOptionPane.showMessageDialog(this, "bạn chưa nhập thông tin muốn tìm kiếm ");
            txt_TKHDCTT.requestFocus();
            
        }else{
            ArrayList<Model_DichVu> KQTK = rp.TK_HDTrongDDV(maTK);
            if (KQTK == null) {
                JOptionPane.showMessageDialog(this, "Thông tin không tồn tại");
                
            }else{
                JOptionPane.showMessageDialog(this, "Đã tìm thấy thông tin");
                this.fillTable_HDDDV(KQTK);
            }
        }
    }//GEN-LAST:event_txt_TKHDCTTActionPerformed

    private void tbn_TKCHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_TKCHDActionPerformed
        // TODO add your handling code here:
        String maTK = txt_TKHDCTT.getText().trim();
        if(maTK.isEmpty()){
            JOptionPane.showMessageDialog(this, "bạn chưa nhập thông tin muốn tìm kiếm ");
            txt_TKHDCTT.requestFocus();
            
        }else{
            ArrayList<Model_DichVu> KQTK = rp.TK_HDTrongDDV(maTK);
            if (KQTK.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Thông tin không tồn tại");
                
            }else{
                JOptionPane.showMessageDialog(this, "Đã tìm thấy thông tin");
                this.fillTable_HDDDV(KQTK);
            }
        }
    }//GEN-LAST:event_tbn_TKCHDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txt_maHD.setText("");
        txt_maDV.setText("");
        txt_gia.setText("");
        txt_maDDV.setText("");
        txt_maPhong.setText("");
        txt_tenDV.setText("");
        txt_tongTien.setText("");
        jsp_SL.setValue(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_maDV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maDV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maDV1ActionPerformed

    private void btn_luu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luu1ActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn hủy dịch vụ");
        i = tbl_HDV.getSelectedRow();
        if(chon == 0){
            if (i == -1) {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn đơn đặt dịch vụ muốn xóa");
            }else{
                String maDDV = tbl_HDV.getValueAt(i, 0).toString();
                if (this.readForm()!= null) {
                    if (rp.huyDV(maDDV)>0) {
                        JOptionPane.showMessageDialog(this, "Hủy Dịch Vụ Thành Công");
                        this.fillTable_HDV(rp.getALL_HDV());
                    }else{
                        JOptionPane.showMessageDialog(this, "do 1 lỗi nào đó hủy thất bại vui lòng kiểm tra lại");
                    }
                }
                
            }
        }
    }//GEN-LAST:event_btn_luu1ActionPerformed

    private void btn_cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancel1ActionPerformed

    private void tbl_HDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HDVMouseClicked
        // TODO add your handling code here:
        i = tbl_HDV.getSelectedRow();
        txt_maDDV1.setText(tbl_HDV.getValueAt(i, 0).toString());
        txt_maPhong1.setText(tbl_HDV.getValueAt(i, 1).toString());
        txt_maDV1.setText(tbl_HDV.getValueAt(i, 2).toString());
        txt_tenDV1.setText(tbl_HDV.getValueAt(i, 3).toString());
        jsp_SL1.setValue(tbl_HDV.getValueAt(i, 4));
        txt_gia1.setText(tbl_HDV.getValueAt(i, 5).toString());
        txt_tongTien1.setText(tbl_HDV.getValueAt(i, 7).toString());
        txt_maHD1.setText(tbl_HDV.getValueAt(i, 8).toString());
    }//GEN-LAST:event_tbl_HDVMouseClicked

    private void tbn_TKHDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_TKHDVActionPerformed
        // TODO add your handling code here:
        String maTK1 = txt_TKHDV.getText().trim();
        
        if (maTK1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập thông tin muốn tìm kiếm");
            
        }else{
            ArrayList<Model_DichVu> KQTK = rp.timKiem_HDV(maTK1);
            if (KQTK.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không có thông tin muốn tìm");
            }else{
                JOptionPane.showMessageDialog(this, "Đã tìm thấy thông tin");
                this.fillTable_HDV(KQTK);
            }
        }
    }//GEN-LAST:event_tbn_TKHDVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_DichVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Xóa;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_cancel1;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_luu1;
    private javax.swing.JButton btn_tinhToan;
    private javax.swing.JComboBox<String> cbo_LoaiDV;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner jsp_SL;
    private javax.swing.JSpinner jsp_SL1;
    private javax.swing.JTable tbl_DDV;
    private javax.swing.JTable tbl_DV;
    private javax.swing.JTable tbl_HDCTT;
    private javax.swing.JTable tbl_HDV;
    private javax.swing.JButton tbn_Cancel;
    private javax.swing.JButton tbn_Reset;
    private javax.swing.JButton tbn_Sửa;
    private javax.swing.JButton tbn_TK;
    private javax.swing.JButton tbn_TKCDV;
    private javax.swing.JButton tbn_TKCHD;
    private javax.swing.JButton tbn_TKHDV;
    private javax.swing.JButton tbn_ThemDV;
    private javax.swing.JTextField txt_Gia;
    private javax.swing.JTextArea txt_MT;
    private javax.swing.JTextField txt_MaDV;
    private javax.swing.JTextField txt_TK;
    private javax.swing.JTextField txt_TKDV_DDV;
    private javax.swing.JTextField txt_TKHDCTT;
    private javax.swing.JTextField txt_TKHDV;
    private javax.swing.JTextField txt_TenDV;
    private javax.swing.JTextField txt_gia;
    private javax.swing.JTextField txt_gia1;
    private javax.swing.JTextField txt_maDDV;
    private javax.swing.JTextField txt_maDDV1;
    private javax.swing.JTextField txt_maDV;
    private javax.swing.JTextField txt_maDV1;
    private javax.swing.JTextField txt_maHD;
    private javax.swing.JTextField txt_maHD1;
    private javax.swing.JTextField txt_maPhong;
    private javax.swing.JTextField txt_maPhong1;
    private javax.swing.JTextField txt_tenDV;
    private javax.swing.JTextField txt_tenDV1;
    private javax.swing.JTextField txt_tongTien;
    private javax.swing.JTextField txt_tongTien1;
    // End of variables declaration//GEN-END:variables
    private void showDaTa_DV(int i) {
        txt_MaDV.setText(tbl_DV.getValueAt(i, 0).toString());
        txt_TenDV.setText(tbl_DV.getValueAt(i, 1).toString());
        txt_Gia.setText(tbl_DV.getValueAt(i, 2).toString());
        cbo_LoaiDV.setSelectedItem(tbl_DV.getValueAt(i, 3));
        txt_MT.setText(tbl_DV.getValueAt(i, 4).toString());
    }
    private void showDaTa_DDV(int i) {
        txt_maDV.setText(tbl_DDV.getValueAt(i, 0).toString());
        txt_tenDV.setText(tbl_DDV.getValueAt(i, 1).toString());
        txt_gia.setText(tbl_DDV.getValueAt(i, 2).toString());
        
    }
    private void showDaTa_HDDDV(){
        txt_maHD.setText(tbl_HDCTT.getValueAt(i, 0).toString());
        txt_maPhong.setText(tbl_HDCTT.getValueAt(i, 1).toString());
    }
    
    

    private Model_DichVu readForm(){
        String maDV = txt_MaDV.getText().trim();
        if (maDV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "chưa điền mã dịch vụ");
            txt_MaDV.requestFocus();
            return null;
        }
        String tenDV = txt_TenDV.getText().trim();
        if (tenDV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "chưa điền tên dịch vụ");
            txt_TenDV.requestFocus();
            return null;
        }
        String checkTrongGia = txt_Gia.getText().trim();
        double gia;
        if (checkTrongGia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập giá dịch vụ");
            txt_Gia.requestFocus();
            return null;
        } else {
            try {
                gia = Double.parseDouble(checkTrongGia);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "nhập sai định dạng giá dịch vụ");
                txt_Gia.requestFocus();
                return null;
            }

        }

        String loaiDV = cbo_LoaiDV.getSelectedItem().toString().trim();
        String moTa = txt_MT.getText().trim();
        if (moTa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "chưa điền mô tả");
            txt_MT.requestFocus();
            return null;
        }
       
        return new Model_DichVu(maDV, tenDV, gia, loaiDV, moTa);
    }
    
    private Model_DichVu readForm_DDV(){
       String maDDV = txt_maDDV.getText().trim();
        if (maDDV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập mã đặt dịch vụ");
            txt_maDDV.requestFocus();
            return null;
        }
       String maDV = txt_maDV.getText().trim();
        if (maDV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa chọn dịch vụ muốn đặt. Mời chọn dịch vụ ở phần chọn dịch vụ ở phần chọn dịch vụ");
            return null;
        }
       String tenDV = txt_tenDV.getText().trim();
       String maHD = txt_maHD.getText().trim();
        if (maHD.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa chọn thông tin của hóa đơn cho dịch vụ này, mời chọn hóa đơn ở phần hóa đơn chưa thanh toán");
            return null;
        }
       String maP = txt_maPhong.getText().trim();
       int sL = Integer.parseInt(String.valueOf(jsp_SL.getValue())) ;
        if (sL <=0) {
            JOptionPane.showMessageDialog(this, "số lượng không hợp lệ mời nhập lại");
            jsp_SL.requestFocus();
            return null;
        }
        
       double gia = Double.parseDouble(txt_gia.getText().trim());
       
      String checkTT = txt_tongTien.getText().trim();
        if (checkTT.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa tính tổng tiền, Mời bấm vào ô tính toán để tính tiền cho lần đặt dịch vụ này");
           return null;
        }
        double tongTien = Double.parseDouble(txt_tongTien.getText().trim());
       return new Model_DichVu(maDDV, maP, maDV, tenDV, sL, gia, tongTien, maHD);
    }
    // readform hủy dịch vụ
    
    private Model_DichVu readForm_HDV(){
        String maDDV = txt_maDDV1.getText().trim();
        String maP = txt_maPhong1.getText().trim();
        String maDV = txt_maDV1.getText().trim();
        String tenDV = txt_tenDV1.getText().trim();
        int soL = Integer.parseInt(jsp_SL1.getValue().toString()) ;
        double gia = Double.parseDouble(txt_gia1.getText().trim());
        Date ngayDat = null;
        double tongTien = Double.parseDouble(txt_tongTien1.getText().trim());
        String maHD = txt_maHD1.getText().trim();
        return new Model_DichVu(maDDV, maP, maDV, tenDV, soL, gia, tongTien, maHD);
    }
    
    
    //private Model_DichVu readFormDDV(){
   /* String maHD = txt_maHD.getText().trim();
       if(maHD.isEmpty()){
           JOptionPane.showMessageDialog(this, "Chưa Điền Mã Hóa Đơn");
           txt_maHD.requestFocus();
           return null;
       }
    String maDV = txt_maDV.getText().trim();
    if(maDV.isEmpty()){
           JOptionPane.showMessageDialog(this, "Chưa Điền Mã Dịch Vụ");
           txt_maDV.requestFocus();
           return null;
       }
    String maDDV = txt_maDDV.getText().trim();
    if(maDDV.isEmpty()){
           JOptionPane.showMessageDialog(this, "Chưa Điền Mã Đặt Dịch Vụ");
           txt_maDDV.requestFocus();
           return null;
       }
    String tenDV = txt_tenDV.getText().trim();
    if(tenDV.isEmpty()){
           JOptionPane.showMessageDialog(this, "Chưa Điền Tên Dịch Vụ");
           txt_tenDV.requestFocus();
           return null;
       }
    double gia = Double.parseDouble(txt_gia.getText().trim()) ;
    if(gia.isEmpty()){
           JOptionPane.showMessageDialog(this, "Chưa Điền Giá Dịch Vụ");
           txt_gia.requestFocus();
           return null;
       }
    int soLuong = Integer.parseInt(jsp_SL.getValue().toString().trim());
    
     double tongTien = Double.parseDouble(txt_tongTien.getText().trim());
   if(tongTien.isEmpty()){
           JOptionPane.showMessageDialog(this, "Chưa Có Tổng Tiền");
           txt_tongTien.requestFocus();
           return null;
       }
   String maPhong = txt_maPhong.getText().trim();
   if(maPhong.isEmpty()){
           JOptionPane.showMessageDialog(this, "Chưa Điền Mã Phòng");
           txt_maHD.requestFocus();
           return null;
       }
   return new Model_DichVu(maDDV, maDV, maDV, tenDV, soLuong, gia, tongTien, maHD);
*/
   // }

}
